# Author: Manuel Alejandro Rodriguez Diaz, PhD
"""Tests for the Markdown reference-case format, its parser and the runner."""

import math
import subprocess
import sys
import tomllib
from pathlib import Path

import pytest

from ventorum.reference import analytic
from ventorum.reference.database import (
    MACH_LIMIT,
    ReferenceCase,
    ReferenceError,
    load_case,
)

REPO = Path(__file__).resolve().parents[1]
DATA_DIR = REPO / "tests" / "data" / "reference"
RUNNER = REPO / "validation" / "run_validation.py"

AR = 6.0
ALPHAS_DEG = [-2.0, 0.0, 2.0, 4.0, 6.0, 8.0]


def _cl_values():
    """CL of an elliptic wing from Lanchester–Prandtl theory (never typed)."""
    cla = analytic.elliptic_wing_cl_alpha(AR)
    return [cla * math.radians(a) for a in ALPHAS_DEG]


def _sections_toml(n=25):
    """TOML rows for an elliptic planform with span 6 m and AR 6 (computed)."""
    root_chord = 4.0 / math.pi  # m, from S = b^2 / AR with an elliptic planform of span 6 m
    lines = []
    for i in range(n):
        eta = i / (n - 1)
        chord = max(root_chord * math.sqrt(max(1.0 - eta * eta, 0.0)), 1.0e-3 * root_chord)
        lines.append(f"  {{ y_frac = {eta:.6f}, chord_m = {chord:.6f} }},")
    return "\n".join(lines)


def _valid_toml(case_id="elliptic_synthetic", **overrides):
    """A valid TOML block; overrides replace whole lines by key prefix."""
    body = f"""[identity]
id = "{case_id}"
title = "Elliptic wing, synthetic theory case"
entry_version = 1

[source]
citation = "L. Prandtl, Tragflugeltheorie I/II, 1918-1919 (closed form, generated by the test)"
doi_or_url = "https://example.org/prandtl-1918"
location = "Closed form CL_alpha = a0 / (1 + a0 / (pi AR))"
type = "theory"
synthetic = true

[geometry]
span_m = 6.0
sections = [
{_sections_toml()}
]

[conditions]
mach = 0.1
reynolds = 1000000.0
beta_deg = 0.0
corrections = "none (synthetic case)"

[[results]]
quantity = "CL"
alpha_deg = [{", ".join(f"{a:.1f}" for a in ALPHAS_DEG)}]
values = [{", ".join(f"{v:.10f}" for v in _cl_values())}]
uncertainty = 0.02
uncertainty_kind = "absolute"
extraction = "table"

[quality]
notes = "Synthetic case for the parser tests."
"""
    for key, replacement in overrides.items():
        lines = []
        for line in body.splitlines():
            if line.strip().startswith(key):
                if replacement is not None:
                    lines.append(replacement)
            else:
                lines.append(line)
        body = "\n".join(lines) + "\n"
    return body


def _write_md(path, case_id="elliptic_synthetic", **overrides):
    path.write_text(
        f"# Case {case_id}\n\nFree text for people.\n\n```toml\n{_valid_toml(case_id, **overrides)}```\n",
        encoding="utf-8",
    )
    return path


def write_elliptic_synthetic(path):
    """Write the valid synthetic case (values computed from the formula)."""
    return _write_md(Path(path), "elliptic_synthetic")


def test_load_valid_case(tmp_path):
    path = write_elliptic_synthetic(tmp_path / "elliptic_synthetic.md")
    case = load_case(path)
    assert isinstance(case, ReferenceCase)
    assert case.id == "elliptic_synthetic"
    assert case.synthetic is True
    assert case.source_type == "theory"
    assert len(case.results) == 1
    res = case.results[0]
    assert res.quantity == "CL"
    assert list(res.alpha_deg) == pytest.approx(ALPHAS_DEG)
    assert list(res.values) == pytest.approx(_cl_values())
    assert res.abs_uncertainty == pytest.approx([0.02] * len(ALPHAS_DEG))
    assert case.aircraft.S_ref == pytest.approx(6.0, abs=0.05)
    assert case.aircraft.b_ref == pytest.approx(6.0)


def test_valid_synthetic_file_in_repo():
    """The committed file holds the values of the formula (the test only reads it)."""
    case = load_case(DATA_DIR / "elliptic_synthetic.md")
    assert case.id == "elliptic_synthetic"
    assert list(case.results[0].values) == pytest.approx(_cl_values())


def test_theory_case_has_no_grade():
    """A theory case loads without a grade and reports grade None."""
    case = load_case(DATA_DIR / "elliptic_synthetic.md")
    assert case.source_type == "theory"
    assert case.grade is None


def test_theory_case_with_grade_is_refused():
    """A theory case that carries a grade is refused, naming file and field."""
    with pytest.raises(ReferenceError) as exc:
        load_case(DATA_DIR / "broken_theory_grade.md")
    message = str(exc.value)
    assert "broken_theory_grade.md" in message
    assert "source.grade" in message
    assert "theory cases have no grade" in message


def test_experiment_without_grade_is_refused(tmp_path):
    path = _write_md(tmp_path / "case_experiment.md", "case_experiment", type='type = "experiment"')
    with pytest.raises(ReferenceError) as exc:
        load_case(path)
    assert "case_experiment.md" in str(exc.value) and "grade" in str(exc.value)


def test_missing_field_is_refused(tmp_path):
    path = _write_md(tmp_path / "case_missing.md", "case_missing", location=None)
    with pytest.raises(ReferenceError) as exc:
        load_case(path)
    assert "case_missing.md" in str(exc.value) and "location" in str(exc.value)


def test_todo_value_is_refused(tmp_path):
    path = _write_md(
        tmp_path / "case_todo.md", "case_todo", corrections='corrections = "TODO wind-tunnel corrections"'
    )
    with pytest.raises(ReferenceError) as exc:
        load_case(path)
    assert "case_todo.md" in str(exc.value) and "corrections" in str(exc.value)


def test_length_mismatch_is_refused(tmp_path):
    path = _write_md(
        tmp_path / "case_lengths.md", "case_lengths", values="values = [0.1, 0.2]"
    )
    with pytest.raises(ReferenceError) as exc:
        load_case(path)
    assert "case_lengths.md" in str(exc.value) and "values" in str(exc.value)


def test_unknown_quantity_is_refused(tmp_path):
    path = _write_md(
        tmp_path / "case_quantity.md", "case_quantity", quantity='quantity = "CK"'
    )
    with pytest.raises(ReferenceError) as exc:
        load_case(path)
    assert "case_quantity.md" in str(exc.value) and "CK" in str(exc.value)


def _run_runner(db, out, extra=()):
    env = {
        "PYTHONPATH": str(REPO),
        "MPLBACKEND": "Agg",
        "PATH": __import__("os").environ.get("PATH", ""),
        "SYSTEMROOT": __import__("os").environ.get("SYSTEMROOT", ""),
    }
    proc = subprocess.run(
        [sys.executable, str(RUNNER), "--db", str(db), "--out", str(out), *extra],
        capture_output=True,
        text=True,
        env=env,
        timeout=600,
    )
    return proc


def test_runner_writes_a_report(tmp_path):
    out = tmp_path / "report.md"
    proc = _run_runner(DATA_DIR, out)
    assert proc.returncode == 0, proc.stderr
    text = out.read_text(encoding="utf-8")
    assert "elliptic_synthetic" in text
    assert "synthetic" in text.lower()
    assert "| alpha" in text.lower() or "| Alpha" in text


def test_synthetic_cases_are_not_counted(tmp_path):
    db = tmp_path / "db"
    db.mkdir()
    write_elliptic_synthetic(db / "elliptic_synthetic.md")
    out = tmp_path / "report.md"
    proc = _run_runner(db, out)
    assert proc.returncode == 0, proc.stderr
    text = out.read_text(encoding="utf-8")
    assert "not counted" in text.lower()
    assert "Reference points counted: 0" in text


def test_theory_cases_are_shown_not_counted(tmp_path):
    """A theory case is shown in its own section with the same table, not counted."""
    db = tmp_path / "db"
    db.mkdir()
    _write_md(db / "theory_case.md", "theory_case", synthetic="synthetic = false")
    out = tmp_path / "report.md"
    proc = _run_runner(db, out)
    assert proc.returncode == 0, proc.stderr
    text = out.read_text(encoding="utf-8")
    assert "Theory cases (verification, not counted)" in text
    assert "\n### theory_case" in text
    assert "\n## theory_case" not in text
    assert text.index("Theory cases (verification, not counted)") < text.index("### theory_case")
    assert "| alpha [deg] | reference | uncertainty | Ventorum | difference | inside |" in text
    assert "Theory cases shown: 1" in text
    assert "Reference points counted: 0" in text
    assert "Cases counted: 0" in text


def test_outside_envelope_is_listed_not_run(tmp_path):
    db = tmp_path / "db"
    db.mkdir()
    _write_md(db / "fast_case.md", "fast_case", mach="mach = 0.5")
    out = tmp_path / "report.md"
    proc = _run_runner(db, out)
    assert proc.returncode == 0, proc.stderr
    text = out.read_text(encoding="utf-8")
    assert "fast_case" in text
    assert "outside the envelope" in text.lower()
    assert str(MACH_LIMIT) in text
    assert "not run" in text.lower()


def _write_height_case(path, case_id, alphas, h_list=None, height_point=None, scalar_h=None):
    """Write a synthetic case with a scalar height, a height list, or neither."""
    cla = analytic.elliptic_wing_cl_alpha(AR)
    vals = [cla * math.radians(a) for a in alphas]
    result_lines = [
        "[[results]]",
        'quantity = "CL"',
        f"alpha_deg = [{', '.join(f'{a:.1f}' for a in alphas)}]",
        f"values = [{', '.join(f'{v:.10f}' for v in vals)}]",
    ]
    if h_list is not None:
        result_lines.append(f"h_m = [{', '.join(f'{h:.3f}' for h in h_list)}]")
    if height_point is not None:
        result_lines.append(f"height_point = [{', '.join(f'{p:.3f}' for p in height_point)}]")
    result_lines.append('extraction = "table"')
    cond_h = f"\nh_m = {scalar_h:.3f}" if scalar_h is not None else ""
    results_text = "\n".join(result_lines)
    Path(path).write_text(
        f"# Case {case_id}\n\nFree text for people.\n\n```toml\n"
        f"[identity]\nid = \"{case_id}\"\ntitle = \"Synthetic height case\"\nentry_version = 1\n\n"
        "[source]\ncitation = \"Synthetic case for the height-per-point tests\"\n"
        'location = "Generated by the test"\ntype = "experiment"\ngrade = "C"\nsynthetic = true\n\n'
        "[geometry]\nspan_m = 6.0\nchord_m = 1.0\n\n"
        "[conditions]\nmach = 0.1\nreynolds = 1000000.0\nbeta_deg = 0.0"
        f'{cond_h}\ncorrections = "none (synthetic case)"\n\n'
        f"{results_text}\n\n"
        '[quality]\nnotes = "Synthetic case for the height-per-point tests."\n```\n',
        encoding="utf-8",
    )
    return Path(path)


def _runner_module():
    """Load validation/run_validation.py as a module (no subprocess, faster tests)."""
    import importlib.util

    spec = importlib.util.spec_from_file_location("run_validation", REPO / "validation" / "run_validation.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_height_list_is_read(tmp_path):
    """A result with a h_m list loads, and the list is on the result."""
    path = _write_height_case(tmp_path / "height_list.md", "height_list", [0.0, 4.0], h_list=[1.5, 2.0])
    case = load_case(path)
    assert list(case.results[0].h_m) == pytest.approx([1.5, 2.0])
    assert case.results[0].height_point is None
    assert case.h_m is None


def test_height_length_mismatch_is_refused():
    """A h_m list shorter than alpha_deg is refused, naming file and field."""
    with pytest.raises(ReferenceError) as exc:
        load_case(DATA_DIR / "broken_height_length.md")
    message = str(exc.value)
    assert "broken_height_length.md" in message
    assert "h_m" in message


def test_height_nonpositive_value_is_refused():
    """A h_m list with a value that is not > 0 is refused, naming file and field."""
    with pytest.raises(ReferenceError) as exc:
        load_case(DATA_DIR / "broken_height_value.md")
    message = str(exc.value)
    assert "broken_height_value.md" in message
    assert "h_m" in message


def test_height_point_shape_is_refused():
    """A height_point without 3 numbers is refused, naming file and field."""
    with pytest.raises(ReferenceError) as exc:
        load_case(DATA_DIR / "broken_height_point_shape.md")
    message = str(exc.value)
    assert "broken_height_point_shape.md" in message
    assert "height_point" in message


def test_height_point_without_list_is_refused():
    """A height_point without a h_m list is refused, naming file and field."""
    with pytest.raises(ReferenceError) as exc:
        load_case(DATA_DIR / "broken_height_point_alone.md")
    message = str(exc.value)
    assert "broken_height_point_alone.md" in message
    assert "height_point" in message
    assert "h_m" in message


def test_height_list_matches_scalar(tmp_path):
    """The same height for every point gives the same Ventorum values as the scalar h_m."""
    alphas = [0.0, 4.0]
    case_scalar = load_case(_write_height_case(tmp_path / "h_scalar.md", "h_scalar", alphas, scalar_h=1.0))
    case_listed = load_case(
        _write_height_case(tmp_path / "h_listed.md", "h_listed", alphas, h_list=[1.0, 1.0])
    )
    mod = _runner_module()
    rows_scalar = mod.run_result(case_scalar, case_scalar.results[0], "vlm")
    rows_listed = mod.run_result(case_listed, case_listed.results[0], "vlm")
    assert all(r[7] is None for r in rows_scalar + rows_listed)
    for row_s, row_l in zip(rows_scalar, rows_listed):
        assert abs(row_s[3] - row_l[3]) <= 1e-12


def test_height_point_offset(tmp_path):
    """A height_point away from the reference point converts to the solved height."""
    import numpy as np

    import ventorum as vt
    from ventorum.aero.system import ground_normal

    alphas = [0.0, 4.0]
    h_list = [1.5, 1.5]
    height_point = [1.0, 0.0, 0.0]
    case = load_case(
        _write_height_case(
            tmp_path / "h_offset.md", "h_offset", alphas, h_list=h_list, height_point=height_point
        )
    )
    mod = _runner_module()
    rows = mod.run_result(case, case.results[0], "vlm")
    solve_ref = np.zeros(3)
    for row, alpha_deg, h_point in zip(rows, alphas, h_list):
        assert row[7] is None
        k = ground_normal(float(np.radians(alpha_deg)), float(np.radians(case.beta_deg)))
        h_ref = h_point + float((solve_ref - np.array(height_point)) @ k)
        # Independent check of the sign: x is aft, so with the nose up the
        # height point 1 m aft is lower, and the origin is higher by sin(alpha).
        assert abs(h_ref - (h_point + np.sin(np.radians(alpha_deg)))) <= 1e-12
        assert h_ref > 0.0
        condition = vt.FlightCondition(
            V_inf=case.mach * mod.SPEED_OF_SOUND_M_S,
            alpha=float(np.radians(alpha_deg)),
            beta=float(np.radians(case.beta_deg)),
            rho=mod.RHO_KG_M3,
            h=h_ref,
        )
        settings = vt.SolverSettings(solver_type="vlm", n_panels=mod.N_PANELS)
        direct = float(vt.analyze(case.aircraft, condition=condition, settings=settings).totals.CL)
        assert abs(row[3] - direct) <= 1e-12


def test_height_below_ground_is_an_error(tmp_path):
    """A point with converted height not > 0 is an error; the other points still run."""
    case = load_case(
        _write_height_case(
            tmp_path / "h_strike.md",
            "h_strike",
            [0.0, 4.0],
            h_list=[0.5, 2.0],
            height_point=[0.0, 0.0, 1.0],
        )
    )
    mod = _runner_module()
    rows = mod.run_result(case, case.results[0], "vlm")
    assert rows[0][7] is not None
    assert rows[1][7] is None
    assert rows[1][3] is not None


def test_report_shows_heights(tmp_path):
    """A result with a h_m list gets a h [m] column; a result without one does not."""
    case_plain = load_case(_write_height_case(tmp_path / "plain_case.md", "plain_case", [0.0, 4.0]))
    case_height = load_case(
        _write_height_case(
            tmp_path / "height_case.md", "height_case", [0.0, 4.0], h_list=[1.5, 2.0]
        )
    )
    mod = _runner_module()
    text, _ = mod.build_report(tmp_path, [case_plain, case_height], [], [], "vlm")
    assert text.count("| alpha [deg] | h [m] |") == 1
    assert "| alpha [deg] | reference |" in text


def test_template_parses():
    template = REPO / "validation" / "reference_template.md"
    block = template.read_text(encoding="utf-8").split("```toml")[1].split("```")[0]
    data = tomllib.loads(block)
    assert data["identity"]["id"] == "template_example"
