# Author: Manuel Alejandro Rodriguez Diaz, PhD
"""
Tests for validation/compare_reports.py (task T-0010, decision 5).

The script must ignore the run-time line and the environment line, accept
round-off differences in numbers, and reject a changed result or a changed
text. The tests run the script as a process and check the exit status.
"""

import subprocess
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "validation" / "compare_reports.py"

CONTENT = (
    "| AR | CL_alpha | error |\n"
    "|---|---|---|\n"
    "| 8 | 5.0267 | +0.002 % |\n"
    "\n"
    "Limits: 1000000.0000001 and 1.2345678901234567e-16.\n"
    "\n"
)


def _report(content: str = CONTENT, run_time: str = "17.5",
            environment: str = "on 2026-01-01 (Python 3.12.0, numpy 2.1.0)") -> str:
    """Build a report with one content body, one run-time line and one environment line."""
    return (
        "# Ventorum verification report\n"
        "\n"
        f"Generated by `validation/run_verification.py` {environment}. All numbers are computed by "
        "the script; there are no hard-coded results.\n"
        "\n"
        f"{content}"
        f"Run time: {run_time} s.\n"
    )


def _compare(tmp_path, old_text: str, new_text: str) -> subprocess.CompletedProcess:
    old = tmp_path / "old.md"
    new = tmp_path / "new.md"
    old.write_text(old_text, encoding="utf-8")
    new.write_text(new_text, encoding="utf-8")
    return subprocess.run(
        [sys.executable, str(SCRIPT), str(old), str(new)],
        capture_output=True, text=True, encoding="utf-8", timeout=60,
    )


def test_changed_number_fails(tmp_path):
    proc = _compare(tmp_path, _report(), _report(CONTENT.replace("5.0267", "5.0268")))
    assert proc.returncode == 1
    # The differences are printed.
    assert "5.0268" in proc.stdout


def test_changed_text_fails(tmp_path):
    proc = _compare(tmp_path, _report(), _report(CONTENT.replace("CL_alpha", "CL_beta")))
    assert proc.returncode == 1
    assert "CL_beta" in proc.stdout


def test_missing_line_fails(tmp_path):
    shorter = CONTENT.replace("| 8 | 5.0267 | +0.002 % |\n", "")
    proc = _compare(tmp_path, _report(), _report(shorter))
    assert proc.returncode == 1


def test_round_off_change_passes(tmp_path):
    # The absolute tolerance 1e-12 catches the change of the tiny number, and
    # the relative tolerance 1e-9 catches the change of the large number.
    changed = CONTENT.replace(
        "1000000.0000001 and 1.2345678901234567e-16",
        "1000000.0000002 and 1.2345678901234569e-16",
    )
    proc = _compare(tmp_path, _report(), _report(changed))
    assert proc.returncode == 0, proc.stdout


def test_changed_run_time_line_passes(tmp_path):
    proc = _compare(tmp_path, _report(run_time="17.5"), _report(run_time="42.0"))
    assert proc.returncode == 0, proc.stdout


def test_changed_environment_line_passes(tmp_path):
    old = _report(environment="on 2026-01-01 (Python 3.12.0, numpy 2.1.0)")
    new = _report(environment="on 2026-06-06 (Python 3.13.1, numpy 2.2.3)")
    proc = _compare(tmp_path, old, new)
    assert proc.returncode == 0, proc.stdout


def test_identical_reports_pass(tmp_path):
    proc = _compare(tmp_path, _report(), _report())
    assert proc.returncode == 0, proc.stdout
