"""Compare two verification reports line by line.

The script checks that a newly generated verification report matches a
committed report. The comparison ignores lines that change on every run
(run time and environment). Text must match exactly. Numbers may differ by
round-off only.

Reference: the verification rules in ``validation/`` and the report format
written by ``validation/run_verification.py``.

Parameters
----------
old_path : str
    Path of the committed report, for example
    ``docs/verification_report.md``.
new_path : str
    Path of the report that was generated in this run.

Returns
-------
int
    Exit code 0 when the reports match, 1 when they differ, 2 on a usage
    error.

Notes
-----
A number passes when ``abs(a - b) <= 1e-12`` or when
``abs(a - b) <= 1e-9 * max(abs(a), abs(b))``. A NaN in both reports counts
as equal. The tolerance is a relative round-off bound. It is not a physics
tolerance. Do not widen it to make a real change pass.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

#: Absolute tolerance for round-off in a number, in report units.
ABS_TOL = 1e-12
#: Relative tolerance for round-off in a number, dimensionless.
REL_TOL = 1e-9

#: Prefixes of the lines that change on every run and are ignored.
IGNORED_PREFIXES = ("Run time:", "Generated by")

NUMBER_RE = re.compile(
    r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?"
)


def ignore_line(line: str) -> bool:
    """Return True when the line changes on every run.

    Parameters
    ----------
    line : str
        One report line without the end-of-line marker.

    Returns
    -------
    bool
        True for the run-time line and the environment line.
    """
    stripped = line.strip()
    return stripped.startswith(IGNORED_PREFIXES)


def numbers_equal(a: float, b: float) -> bool:
    """Return True when two parsed numbers agree to round-off.

    Parameters
    ----------
    a, b : float
        The two numbers parsed from the same position in each line.

    Returns
    -------
    bool
        True when the difference is within the absolute or relative
        round-off bound, or when both numbers are NaN.
    """
    if a != a and b != b:
        return True
    if a == b:
        return True
    diff = abs(a - b)
    if diff <= ABS_TOL:
        return True
    scale = max(abs(a), abs(b))
    return diff <= REL_TOL * scale


def lines_match(old_line: str, new_line: str) -> bool:
    """Return True when two report lines carry the same content.

    Text must match exactly. Numbers may differ by round-off.

    Parameters
    ----------
    old_line, new_line : str
        The two lines without the end-of-line marker.

    Returns
    -------
    bool
        True when the lines match.
    """
    old_parts = NUMBER_RE.split(old_line)
    new_parts = NUMBER_RE.split(new_line)
    if old_parts != new_parts:
        return False
    old_nums = NUMBER_RE.findall(old_line)
    new_nums = NUMBER_RE.findall(new_line)
    for old_token, new_token in zip(old_nums, new_nums):
        if not numbers_equal(float(old_token), float(new_token)):
            return False
    return True


def compare(old_path: str, new_path: str) -> int:
    """Compare two report files.

    Parameters
    ----------
    old_path : str
        Path of the committed report.
    new_path : str
        Path of the generated report.

    Returns
    -------
    int
        Exit code 0 when the reports match, 1 when they differ, 2 when a
        file cannot be read.
    """
    try:
        old_lines = Path(old_path).read_text(encoding="utf-8").splitlines()
        new_lines = Path(new_path).read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        print(f"compare_reports: cannot read a report: {exc}", file=sys.stderr)
        return 2

    old_kept = [line for line in old_lines if not ignore_line(line)]
    new_kept = [line for line in new_lines if not ignore_line(line)]

    if len(old_kept) != len(new_kept):
        print(
            "compare_reports: reports differ\n"
            f"  {old_path}: {len(old_kept)} content lines\n"
            f"  {new_path}: {len(new_kept)} content lines"
        )
        return 1

    for index, (old_line, new_line) in enumerate(zip(old_kept, new_kept), start=1):
        if not lines_match(old_line, new_line):
            print(
                "compare_reports: reports differ at content line "
                f"{index}\n"
                f"  old: {old_line}\n"
                f"  new: {new_line}"
            )
            return 1

    print(
        "compare_reports: reports match "
        f"({len(old_kept)} content lines, "
        f"round-off tolerance {ABS_TOL:g} absolute, {REL_TOL:g} relative)"
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    """Run the comparison from the command line.

    Parameters
    ----------
    argv : list of str, optional
        Arguments without the program name.

    Returns
    -------
    int
        Exit code 0 when the reports match, 1 when they differ, 2 on a
        usage error.
    """
    parser = argparse.ArgumentParser(
        description="Compare two verification reports with round-off tolerance."
    )
    parser.add_argument("old_path", help="committed report, e.g. docs/verification_report.md")
    parser.add_argument("new_path", help="generated report, e.g. the output of run_verification.py")
    args = parser.parse_args(argv)
    return compare(args.old_path, args.new_path)


if __name__ == "__main__":
    raise SystemExit(main())
